import assert from "node:assert/strict";
import {
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {
  fileURLToPath,
} from "node:url";
import {
  spawnSync,
} from "node:child_process";
import test from "node:test";

const repoRoot = path.resolve(
  path.dirname(
    fileURLToPath(import.meta.url),
  ),
  "../../..",
);

test("contract generation CLI writes deterministic standalone TypeScript", async (t) => {
  const directory =
    await mkdtemp(
      path.join(
        os.tmpdir(),
        "etlayer-vs26-cli-",
      ),
    );

  t.after(async () => {
    await rm(
      directory,
      {
        recursive: true,
        force: true,
      },
    );
  });

  const artifactFile =
    path.join(
      directory,
      "artifact.json",
    );
  const outputA =
    path.join(
      directory,
      "a.ts",
    );
  const outputB =
    path.join(
      directory,
      "b.ts",
    );

  await writeFile(
    artifactFile,
    JSON.stringify({
      apiVersion: "v1",
      kind: "Contract",
      projectId: "project-a",
      source: "project",
      contract: {
        id: "account.created@2",
        eventName:
          "account.created",
        version: 2,
        required: {
          "account.id": {
            type: "string",
          },
          "etlayer.producer.kind": {
            type: "string",
            const: "backend",
          },
        },
        forbidden: [
          "experiment.id",
        ],
      },
      lifecycle: null,
      links: {},
    }),
    "utf8",
  );

  for (const output of [
    outputA,
    outputB,
  ]) {
    const result = spawnSync(
      process.execPath,
      [
        path.join(
          repoRoot,
          "scripts/generate-contract-typescript.mjs",
        ),
        "--file",
        artifactFile,
        "--out",
        output,
      ],
      {
        cwd: repoRoot,
        encoding: "utf8",
      },
    );

    assert.equal(
      result.status,
      0,
      result.stderr,
    );
  }

  const first =
    await readFile(
      outputA,
      "utf8",
    );
  const second =
    await readFile(
      outputB,
      "utf8",
    );

  assert.equal(first, second);
  assert.equal(
    first.includes(
      "Generated by ETLayer",
    ),
    true,
  );
  assert.equal(
    first.includes(
      "@etlayer/cloudflare-ingest",
    ),
    false,
  );
});
