import assert from "node:assert/strict";
import {
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {
  spawnSync,
} from "node:child_process";
import test from "node:test";

import {
  generateTypeScriptContractModule,
} from "../src/typescript-contract-generator.js";

function artifact(required, forbidden) {
  return {
    apiVersion: "v1",
    kind: "Contract",
    projectId: "project-a",
    source: "project",
    contract: {
      id: "account.created@2",
      eventName: "account.created",
      version: 2,
      required,
      forbidden,
    },
    lifecycle: null,
    links: {},
  };
}

test("generates deterministic TypeScript from normalized contract semantics", () => {
  const first =
    generateTypeScriptContractModule(
      artifact(
        {
          "plan.id": {
            type: "string",
          },
          "account.id": {
            type: "string",
          },
          "etlayer.producer.kind": {
            type: "string",
            const: "backend",
          },
        },
        [
          "experiment.variant",
          "experiment.id",
        ],
      ),
    );

  const second =
    generateTypeScriptContractModule(
      artifact(
        {
          "etlayer.producer.kind": {
            const: "backend",
            type: "string",
          },
          "account.id": {
            type: "string",
          },
          "plan.id": {
            type: "string",
          },
        },
        [
          "experiment.id",
          "experiment.variant",
          "experiment.id",
        ],
      ),
    );

  assert.equal(first, second);
  assert.match(
    first,
    /export type AccountCreatedV2Attributes/,
  );
  assert.match(
    first,
    /validateAccountCreatedV2Attributes/,
  );
  assert.match(
    first,
    /"experiment\.id"\?: never/,
  );
  assert.equal(
    first.includes(
      "@etlayer/cloudflare-ingest",
    ),
    false,
  );
  assert.equal(
    first.includes(
      "../src/",
    ),
    false,
  );
});

test("generated TypeScript validator executes with Node type stripping", async (t) => {
  const directory =
    await mkdtemp(
      path.join(
        os.tmpdir(),
        "etlayer-vs26-",
      ),
    );

  t.after(async () => {
    await rm(
      directory,
      {
        recursive: true,
        force: true,
      },
    );
  });

  const file =
    path.join(
      directory,
      "contract.ts",
    );
  const source =
    generateTypeScriptContractModule(
      artifact(
        {
          "account.id": {
            type: "string",
          },
          "etlayer.schema.count": {
            type: "integer",
          },
          "etlayer.producer.kind": {
            type: "string",
            const: "backend",
          },
        },
        ["experiment.id"],
      ),
    );

  await writeFile(
    file,
    source +
      `
const valid = validateAccountCreatedV2Attributes({
  "account.id": "account-1",
  "etlayer.schema.count": 2,
  "etlayer.producer.kind": "backend",
});

const invalid = validateAccountCreatedV2Attributes({
  "account.id": "account-1",
  "etlayer.schema.count": 2.5,
  "etlayer.producer.kind": "backend",
  "experiment.id": "exp-1",
});

if (!valid || invalid) process.exit(7);
`,
    "utf8",
  );

  const result = spawnSync(
    process.execPath,
    [
      "--experimental-strip-types",
      file,
    ],
    {
      encoding: "utf8",
    },
  );

  assert.equal(
    result.status,
    0,
    result.stderr,
  );

  assert.equal(
    (await readFile(
      file,
      "utf8",
    )).includes(
      "Generated by ETLayer",
    ),
    true,
  );
});
